In [1]:

import pandas as pd

train = pd.read_csv('/Users/kshitijsrivastava/Downloads/Case study 2/train.csv')
test = pd.read_csv('/Users/kshitijsrivastava/Downloads/Case study 2/test.csv')
train.head(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [2]:
display(train)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [3]:
train.shape

(1460, 81)

In [4]:
test.shape

(1459, 80)

In [5]:
NAs = pd.concat([train.isnull().sum()], axis=1 , keys=['train'])
NAs[NAs.sum(axis=1) > 0]

              train
LotFrontage     259
Alley          1369
MasVnrType        8
MasVnrArea        8
BsmtQual         37
BsmtCond         37
BsmtExposure     38
BsmtFinType1     37
BsmtFinType2     38
Electrical        1
FireplaceQu     690
GarageType       81
GarageYrBlt      81
GarageFinish     81
GarageQual       81
GarageCond       81
PoolQC         1453
Fence          1179
MiscFeature    1406

In [6]:
train["LotFrontage"] = train["LotFrontage"].fillna(train["LotFrontage"].mean())

In [7]:
train["MasVnrArea"] = train["MasVnrArea"].fillna(train["MasVnrArea"].mean())

In [8]:
train["GarageYrBlt"] = train["GarageYrBlt"].fillna(train["GarageYrBlt"].mean())

In [9]:
display(train)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [10]:
NAs = pd.concat([train.isnull().sum()], axis=1 , keys=['train'])
NAs[NAs.sum(axis=1) > 0]

              train
Alley          1369
MasVnrType        8
BsmtQual         37
BsmtCond         37
BsmtExposure     38
BsmtFinType1     37
BsmtFinType2     38
Electrical        1
FireplaceQu     690
GarageType       81
GarageFinish     81
GarageQual       81
GarageCond       81
PoolQC         1453
Fence          1179
MiscFeature    1406

In [11]:
for col in train.dtypes[train.dtypes == "object"].index:\
for_dummy = train.pop(col)
train = pd.concat([train, pd.get_dummies(for_dummy, prefix=col)],axis=1)
train.head

<bound method NDFrame.head of         Id  MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  \
0        1          60         65.0     8450            7            5
1        2          20         80.0     9600            6            8
2        3          60         68.0    11250            7            5
3        4          70         60.0     9550            7            5
4        5          60         84.0    14260            8            5
...    ...         ...          ...      ...          ...          ...
1455  1456          60         62.0     7917            6            5
1456  1457          20         85.0    13175            6            6
1457  1458          70         66.0     9042            7            9
1458  1459          20         68.0     9717            5            6
1459  1460          20         75.0     9937            5            6

      YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1  ...  MiscVal  MoSold  \
0          2003          2003       196.0         706  ...        0       2
1          1976          1976         0.0         978  ...        0       5
2          2001          2002       162.0         486  ...        0       9
3          1915          1970         0.0         216  ...        0       2
4          2000          2000       350.0         655  ...        0      12
...         ...           ...         ...         ...  ...      ...     ...
1455       1999          2000         0.0           0  ...        0       8
1456       1978          1988       119.0         790  ...        0       2
1457       1941          2006         0.0         275  ...     2500       5
1458       1950          1996         0.0          49  ...        0       4
1459       1965          1965         0.0         830  ...        0       6

      YrSold  SalePrice  SaleCondition_Abnorml  SaleCondition_AdjLand  \
0       2008     208500                      0                      0
1       2007     181500                      0                      0
2       2008     223500                      0                      0
3       2006     140000                      1                      0
4       2008     250000                      0                      0
...      ...        ...                    ...                    ...
1455    2007     175000                      0                      0
1456    2010     210000                      0                      0
1457    2010     266500                      0                      0
1458    2010     142125                      0                      0
1459    2008     147500                      0                      0

      SaleCondition_Alloca  SaleCondition_Family  SaleCondition_Normal  \
0                        0                     0                     1
1                        0                     0                     1
2                        0                     0                     1
3                        0                     0                     0
4                        0                     0                     1
...                    ...                   ...                   ...
1455                     0                     0                     1
1456                     0                     0                     1
1457                     0                     0                     1
1458                     0                     0                     1
1459                     0                     0                     1

      SaleCondition_Partial
0                         0
1                         0
2                         0
3                         0
4                         0
...                     ...
1455                      0
1456                      0
1457                      0
1458                      0
1459                      0

[1460 rows x 44 columns]>

In [12]:
# Use numpy to convert to arrays
import numpy as np
# Labels are the values we want to predict
labels = np.array(train['SalePrice'])
# Remove the labels from the features
# axis 1 refers to the columns
features= train.drop('SalePrice', axis = 1)

In [13]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(features, labels, test_size = 0.1, random_state = 100000)

In [14]:
from sklearn.ensemble import RandomForestClassifier
# Instantiate model with 1000 decision trees
rf = RandomForestClassifier()
# Train the model on training data
rf.fit(X_train,Y_train);

In [15]:
y_predict = rf.predict(X_test)

In [16]:
import math
MSE = np.square(np.subtract(Y_test,y_predict)).mean() 
 
RMSE = math.sqrt(MSE)
print("Root Mean Square Error:\n")
print(RMSE)

Root Mean Square Error:

41320.3143731659

In [17]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(Y_test, y_predict)

0.1507582481721664

In [18]:
from sklearn import datasets, linear_model, metrics
reg = linear_model.LinearRegression()
reg.fit(X_train, Y_train)

LinearRegression()

In [19]:
y_predict = reg.predict(X_test)

In [20]:
import math
MSE1 = np.square(np.subtract(Y_test,y_predict)).mean() 
 
RMSE1 = math.sqrt(MSE1)
print("Root Mean Square Error:\n")
print(RMSE1)

Root Mean Square Error:

29617.289838257497

In [21]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(Y_test, y_predict)

0.11992245274500603

In [22]:
from sklearn.tree import DecisionTreeRegressor 
regressor = DecisionTreeRegressor(random_state = 100000) 
  
# fit the regressor with X and Y data
regressor.fit(X_train, Y_train)

DecisionTreeRegressor(random_state=100000)

In [23]:
y_pred = regressor.predict(X_test)

In [24]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(Y_test, y_pred)

0.14493038823854124

In [25]:
import math
MSE1 = np.square(np.subtract(Y_test,y_pred)).mean() 
 
RMSE1 = math.sqrt(MSE1)
print("Root Mean Square Error:\n")
print(RMSE1)

Root Mean Square Error:

34006.2350169406

In [26]:
from sklearn.svm import SVR
# most important SVR parameter is Kernel type. It can be #linear,polynomial or gaussian SVR. We have a non-linear condition #so we can select polynomial or gaussian but here we select RBF(a #gaussian type) kernel.
regressor = SVR(kernel='rbf')
regressor.fit(X_train,Y_train)
#5 Predicting a new result
y_pred = regressor.predict(X_test)

In [27]:
y_pred = regressor.predict(X_test)

In [28]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(Y_test, y_pred)

0.28328472727423076

In [29]:
#using linear regression because we got the best results from it

In [30]:
NAs = pd.concat([test.isnull().sum()], axis=1 , keys=['test'])
NAs[NAs.sum(axis=1) > 0]

              test
MSZoning         4
LotFrontage    227
Alley         1352
Utilities        2
Exterior1st      1
Exterior2nd      1
MasVnrType      16
MasVnrArea      15
BsmtQual        44
BsmtCond        45
BsmtExposure    44
BsmtFinType1    42
BsmtFinSF1       1
BsmtFinType2    42
BsmtFinSF2       1
BsmtUnfSF        1
TotalBsmtSF      1
BsmtFullBath     2
BsmtHalfBath     2
KitchenQual      1
Functional       2
FireplaceQu    730
GarageType      76
GarageYrBlt     78
GarageFinish    78
GarageCars       1
GarageArea       1
GarageQual      78
GarageCond      78
PoolQC        1456
Fence         1169
MiscFeature   1408
SaleType         1

In [31]:
display(test)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [32]:
#using lotfrontage , lotarea , overallqual & overallcondition as parameters only

In [36]:
train_new = train.iloc[:, [0,1,3]]

In [35]:

train["LotFrontage"] = train["LotFrontage"].fillna(train["LotFrontage"].mean())

In [34]:
for col in test.dtypes[test.dtypes == "object"].index:\
for_dummy = test.pop(col)
test = pd.concat([test, pd.get_dummies(for_dummy, prefix=col)],axis=1)
test.head

<bound method NDFrame.head of         Id  MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  \
0     1461          20         80.0    11622            5            6
1     1462          20         81.0    14267            6            6
2     1463          60         74.0    13830            5            5
3     1464          60         78.0     9978            6            6
4     1465         120         43.0     5005            8            5
...    ...         ...          ...      ...          ...          ...
1454  2915         160         21.0     1936            4            7
1455  2916         160         21.0     1894            4            5
1456  2917          20        160.0    20000            5            7
1457  2918          85         62.0    10441            5            5
1458  2919          60         74.0     9627            7            5

      YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1  ...  PoolArea  MiscVal  \
0          1961          1961         0.0       468.0  ...         0        0
1          1958          1958       108.0       923.0  ...         0    12500
2          1997          1998         0.0       791.0  ...         0        0
3          1998          1998        20.0       602.0  ...         0        0
4          1992          1992         0.0       263.0  ...         0        0
...         ...           ...         ...         ...  ...       ...      ...
1454       1970          1970         0.0         0.0  ...         0        0
1455       1970          1970         0.0       252.0  ...         0        0
1456       1960          1996         0.0      1224.0  ...         0        0
1457       1992          1992         0.0       337.0  ...         0      700
1458       1993          1994        94.0       758.0  ...         0        0

      MoSold  YrSold  SaleCondition_Abnorml  SaleCondition_AdjLand  \
0          6    2010                      0                      0
1          6    2010                      0                      0
2          3    2010                      0                      0
3          6    2010                      0                      0
4          1    2010                      0                      0
...      ...     ...                    ...                    ...
1454       6    2006                      0                      0
1455       4    2006                      1                      0
1456       9    2006                      1                      0
1457       7    2006                      0                      0
1458      11    2006                      0                      0

      SaleCondition_Alloca  SaleCondition_Family  SaleCondition_Normal  \
0                        0                     0                     1
1                        0                     0                     1
2                        0                     0                     1
3                        0                     0                     1
4                        0                     0                     1
...                    ...                   ...                   ...
1454                     0                     0                     1
1455                     0                     0                     0
1456                     0                     0                     0
1457                     0                     0                     1
1458                     0                     0                     1

      SaleCondition_Partial
0                         0
1                         0
2                         0
3                         0
4                         0
...                     ...
1454                      0
1455                      0
1456                      0
1457                      0
1458                      0

[1459 rows x 43 columns]>

In [40]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
X_train, X_test1 , Y_train, Y_test = train_test_split(train_new, labels, test_size = 0.1, random_state = 100000)

In [38]:
display(test)

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,PoolArea,MiscVal,MoSold,YrSold,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1461,20,80.0,11622,5,6,1961,1961,0.0,468.0,...,0,0,6,2010,0,0,0,0,1,0
1,1462,20,81.0,14267,6,6,1958,1958,108.0,923.0,...,0,12500,6,2010,0,0,0,0,1,0
2,1463,60,74.0,13830,5,5,1997,1998,0.0,791.0,...,0,0,3,2010,0,0,0,0,1,0
3,1464,60,78.0,9978,6,6,1998,1998,20.0,602.0,...,0,0,6,2010,0,0,0,0,1,0
4,1465,120,43.0,5005,8,5,1992,1992,0.0,263.0,...,0,0,1,2010,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,21.0,1936,4,7,1970,1970,0.0,0.0,...,0,0,6,2006,0,0,0,0,1,0
1455,2916,160,21.0,1894,4,5,1970,1970,0.0,252.0,...,0,0,4,2006,1,0,0,0,0,0
1456,2917,20,160.0,20000,5,7,1960,1996,0.0,1224.0,...,0,0,9,2006,1,0,0,0,0,0
1457,2918,85,62.0,10441,5,5,1992,1992,0.0,337.0,...,0,700,7,2006,0,0,0,0,1,0
1458,2919,60,74.0,9627,7,5,1993,1994,94.0,758.0,...,0,0,11,2006,0,0,0,0,1,0

In [39]:
train_new = train.iloc[:, [2,3,4,5]]

In [41]:
from sklearn import datasets, linear_model
reg = linear_model.LinearRegression()
  
# train the model using the training sets
reg.fit(X_train, Y_train)

LinearRegression()

In [44]:
Y_pred = reg.predict(X_test1)

In [45]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(Y_test, Y_pred)

0.18330507070152957

In [46]:
train_new = train.iloc[:, [4,5]]

In [47]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
X_train, X_test1 , Y_train, Y_test = train_test_split(train_new, labels, test_size = 0.1, random_state = 100000)

In [51]:
from sklearn import datasets, linear_model# Using Skicit-learn to split data into training an# Using Skicit-learn to split data into training and testing sets

reg = linear_model.LinearRegression()
  
# train the model using the training sets
reg.fit(X_train, Y_train)

LinearRegression()

In [52]:
Y_pred = reg.predict(X_test1)

In [53]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(Y_test, Y_pred)

0.18703363639742096

In [54]:
train_new = train.iloc[:, [3,4,5]]
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
X_train, X_test1 , Y_train, Y_test = train_test_split(train_new, labels, test_size = 0.1, random_state = 100000)
from sklearn import datasets, linear_model# Using Skicit-learn to split data into training an# Using Skicit-learn to split data into training and testing sets

reg = linear_model.LinearRegression()
  
# train the model using the training sets
reg.fit(X_train, Y_train)

LinearRegression()

In [55]:
Y_pred = reg.predict(X_test1)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(Y_test, Y_pred)

0.17473123718746938

In [56]:
train_new = train.iloc[:, [2,3]]
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
X_train, X_test1 , Y_train, Y_test = train_test_split(train_new, labels, test_size = 0.1, random_state = 100000)
from sklearn import datasets, linear_model# Using Skicit-learn to split data into training an# Using Skicit-learn to split data into training and testing sets

reg = linear_model.LinearRegression()
  
# train the model using the training sets
reg.fit(X_train, Y_train)
Y_pred = reg.predict(X_test1)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(Y_test, Y_pred)

0.3251995134774758

In [57]:
train_new = train.iloc[:, [2,3,4,5,6]]
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
X_train, X_test1 , Y_train, Y_test = train_test_split(train_new, labels, test_size = 0.1, random_state = 100000)
from sklearn import datasets, linear_model# Using Skicit-learn to split data into training an# Using Skicit-learn to split data into training and testing sets

reg = linear_model.LinearRegression()
  
# train the model using the training sets
reg.fit(X_train, Y_train)
Y_pred = reg.predict(X_test1)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(Y_test, Y_pred)

0.17427376945768044

In [58]:
train_new = train.iloc[:, [2,3,4,5,6,10]]
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
X_train, X_test1 , Y_train, Y_test = train_test_split(train_new, labels, test_size = 0.1, random_state = 100000)
from sklearn import datasets, linear_model# Using Skicit-learn to split data into training an# Using Skicit-learn to split data into training and testing sets

reg = linear_model.LinearRegression()
  
# train the model using the training sets
reg.fit(X_train, Y_train)
Y_pred = reg.predict(X_test1)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(Y_test, Y_pred)

0.1739216531731049

In [59]:
train_new = train.iloc[:, [4,5,10]]
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
X_train, X_test1 , Y_train, Y_test = train_test_split(train_new, labels, test_size = 0.1, random_state = 100000)
from sklearn import datasets, linear_model# Using Skicit-learn to split data into training an# Using Skicit-learn to split data into training and testing sets

reg = linear_model.LinearRegression()
  
# train the model using the training sets
reg.fit(X_train, Y_train)
Y_pred = reg.predict(X_test1)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(Y_test, Y_pred)

0.18658356579843535

In [60]:
train_new = train.iloc[:, [5]]
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
X_train, X_test1 , Y_train, Y_test = train_test_split(train_new, labels, test_size = 0.1, random_state = 100000)
from sklearn import datasets, linear_model# Using Skicit-learn to split data into training an# Using Skicit-learn to split data into training and testing sets

reg = linear_model.LinearRegression()
  
# train the model using the training sets
reg.fit(X_train, Y_train)
Y_pred = reg.predict(X_test1)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(Y_test, Y_pred)

0.33356190708279854

In [61]:
train_new = train.iloc[:, [4]]
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
X_train, X_test1 , Y_train, Y_test = train_test_split(train_new, labels, test_size = 0.1, random_state = 100000)
from sklearn import datasets, linear_model# Using Skicit-learn to split data into training an# Using Skicit-learn to split data into training and testing sets

reg = linear_model.LinearRegression()
  
# train the model using the training sets
reg.fit(X_train, Y_train)
Y_pred = reg.predict(X_test1)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(Y_test, Y_pred)

0.186906829571038

In [62]:
train_new = train.iloc[:, [2,3,4,5,6,7,8,9,10,11,12]]
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
X_train, X_test1 , Y_train, Y_test = train_test_split(train_new, labels, test_size = 0.1, random_state = 100000)
from sklearn import datasets, linear_model# Using Skicit-learn to split data into training an# Using Skicit-learn to split data into training and testing sets

reg = linear_model.LinearRegression()
  
# train the model using the training sets
reg.fit(X_train, Y_train)
Y_pred = reg.predict(X_test1)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(Y_test, Y_pred)

0.15062843069934326

In [63]:
train_new = train.iloc[:, 2:19 ]
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
X_train, X_test1 , Y_train, Y_test = train_test_split(train_new, labels, test_size = 0.1, random_state = 100000)
from sklearn import datasets, linear_model# Using Skicit-learn to split data into training an# Using Skicit-learn to split data into training and testing sets

reg = linear_model.LinearRegression()
  
# train the model using the training sets
reg.fit(X_train, Y_train)
Y_pred = reg.predict(X_test1)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(Y_test, Y_pred)

0.12595069186541266

In [ ]:
train_new.shape

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,MiscVal,MoSold,YrSold,SalePrice,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,65.0,8450,7,5,2003,2003,196.0,706,0,150,...,0,2,2008,208500,0,0,0,0,1,0
1,80.0,9600,6,8,1976,1976,0.0,978,0,284,...,0,5,2007,181500,0,0,0,0,1,0
2,68.0,11250,7,5,2001,2002,162.0,486,0,434,...,0,9,2008,223500,0,0,0,0,1,0
3,60.0,9550,7,5,1915,1970,0.0,216,0,540,...,0,2,2006,140000,1,0,0,0,0,0
4,84.0,14260,8,5,2000,2000,350.0,655,0,490,...,0,12,2008,250000,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,62.0,7917,6,5,1999,2000,0.0,0,0,953,...,0,8,2007,175000,0,0,0,0,1,0
1456,85.0,13175,6,6,1978,1988,119.0,790,163,589,...,0,2,2010,210000,0,0,0,0,1,0
1457,66.0,9042,7,9,1941,2006,0.0,275,0,877,...,2500,5,2010,266500,0,0,0,0,1,0
1458,68.0,9717,5,6,1950,1996,0.0,49,1029,0,...,0,4,2010,142125,0,0,0,0,1,0
1459,75.0,9937,5,6,1965,1965,0.0,830,290,136,...,0,6,2008,147500,0,0,0,0,1,0

Root Mean Square Error:

3.856661838666987e-11